# Generated by Django 4.1.2 on 2023-03-05 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_urlpath'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URLPath',
        ),
    ]
